site_name: Aprende FIWARE en Español
repo_url: https://github.com/smartsdkInfotec/FIWARE_Training
edit_uri: edit/master/docs
site_description: En este sitio encontrarás una guía para desarrollar tu primera aplicación con la tecnología FIWARE. 
docs_dir: 'docs'
theme: readthedocs
pages:
    - Inicio: 'index.md'
    - Introducción: 'introduction.md'
    - El ecosistema FIWARE:
        - 'La plataforma FIWARE': 'ecosistemaFIWARE/plataformaFIWARE.md'
        - 'La nube de FIWARE': 'ecosistemaFIWARE/FIWARELab.md'
        - 'Modelos de datos': 'ecosistemaFIWARE/datamodels.md'
        - Gestión de información de contexto:
            - 'Orion Context Broker': 'ecosistemaFIWARE/ocb.md'
            - 'Modelo NGSI': 'ecosistemaFIWARE/ngsi.md'
            - 'Operaciones en OCB': 'ecosistemaFIWARE/operations.md'
    - Desarrollo de soluciones con FIWARE:
        - 'Caso de estudio': 'casodeestudio/descripcion.md'
        - 'Crea tu unidad de monitoreo': 'sensores/cloudino.md'
        - 'Datos abiertos de la CDMX': 'datosabiertos/airecdmx.md'
       #- 'Additional Documentation': 'references.md'

#
#markdown_extensions: [toc,fenced_code]
extra_css: ["https://fiware.org/style/fiware_readthedocs.css"]
